#
#     ______   ______     __        __  __     __     __  __
#    /\__  _\ /\  __ \   /\ \      /\_\_\_\   /\ \   /\ \/\ \
#    \/_/\ \/ \ \  __ \  \ \ \     \/_/\_\/_  \ \ \  \ \ \_\ \
#       \ \_\  \ \_\ \_\  \ \_\      /\_\/\_\  \ \_\  \ \_____\
#        \/_/   \/_/\/_/   \/_/      \/_/\/_/   \/_/   \/_____/
#
#  Author: Cortez_Romeo
#  Download this plugin for free at:
#  https://minecraftvn.net
#  https://www.spigotmc.org/
#
#  Discord: https://discord.gg/NWbTVddmBM

# For debugging purposes
# Do not enable unless necessary
debug: false

database:
  while-ending-session:
    # [TYPE: SAVE - SAVE_AND_UNLOAD]
    # SAVE: The system will save data to a .yml file but won't unload it from memory
    # SAVE_AND_UNLOAD: The system saves data to a .yml file and unloads it from memory (optimizes performance)
    # Note: Unloaded data can be loaded back if something accesses it
    # Example: A player uses command "/taixiu thongtin <unloaded-data>", then the data will be reloaded
    #
    # RECOMMENDED: USE SAVE_AND_UNLOAD
    type: SAVE_AND_UNLOAD
  while-disabling-plugin:
    # [TYPE: SAVE_ALL - SAVE_LATEST - SAVE_LATEST_AND_DELETE_OLD_DATA]
    # SAVE_ALL: Saves all session data currently in memory to .yml (can take long if data is large)
    # SAVE_LATEST: Only saves the latest session to .yml, ignores the rest
    # SAVE_LATEST_AND_DELETE_OLD_DATA: Deletes all old session data (completed sessions) and keeps only the unfinished one
    #
    # TO MAXIMIZE DATA OPTIMIZATION, USE SAVE_LATEST_AND_DELETE_OLD_DATA
    # HOWEVER, IT'S ALSO RECOMMENDED TO USE SAVE_LATEST (see note above), YOU DON'T NEED TO OVER-OPTIMIZE DATA
    type: SAVE_LATEST
  auto-save:
    enabled: true
    # The lower the time, the more frequently data is saved (safer), but may cause lag if data is large
    # Time in seconds
    time: 600

# Which language file in the languages folder to use for displaying messages
# Available options:
# en - English
# vi - Vietnamese
locale: en

task:
  taiXiuTask:
    # Countdown time for each session result
    # Time in seconds
    time-per-session: 125

# Display money in readable format
# Example: format '#,###', 500000 => displayed as: 500,000
# More info: https://www.baeldung.com/java-decimalformat
format-money: '#,###'

# Currency type used per session
# Each session can use a different type
# Options: VAULT, PLAYERPOINTS
currency-settings:
  default: VAULT
  display-settings:
    VAULT:
      name: '&6Money'
      symbol: '&6$'
    PLAYERPOINTS:
      name: '&bPoints'
      symbol: '&b۞'

# Settings related to betting
bet-settings:
  max-bet: 1000000  # Maximum bet allowed
  min-bet: 500      # Minimum bet allowed
  tax: 0            # Additional tax; 0 = disabled
  disable-while-remaining: 15  # Disable betting when time left is under this threshold
  disable-special: false       # If true, disables special cases like sum = 3 or 18 (where both sides lose)

# Geyser API / Floodgate API
# Used to show forms to Bedrock Edition players
floodgate-settings:
  enabled: true

# Used to broadcast session results to Discord via webhook
# Edit the message content in JSON files in the plugin folder
# How to get webhook: https://youtu.be/G_fRHkHQUNU
discord-webhook-settings:
  webhookURL: ""

# Sound effects configuration
# Sound list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound:
  win:
    enabled: true
    sound-name: ENTITY_PLAYER_LEVELUP
    volume: 1
    pitch: 2
  lose:
    enabled: true
    sound-name: ENTITY_VILLAGER_NO
    volume: 1
    pitch: 1

# Boss bar settings for displaying session info
# Color list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
# Style list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
boss-bar:
  enabled: true
  type:
    playing:
      title: '&#79fb13&lT&#93f222&là&#aeea30&li &#c8e13f&lX&#e3d94d&lỉ&#fdd05c&lu &b#%session% &7| &f%timeLeft% Seconds &7| %currencySymbol%%totalBet% %currencySymbol%&#1fc433%xiuBet% %currencySymbol%&#c42d1f%taiBet%'
      color:
        playing: YELLOW
        bet-disabling: BLUE
        pausing: BLUE
      style: SOLID
    reloading:
      enabled: true
      time: 5
      title: '&#79fb13&lT&#93f222&là&#aeea30&li &#c8e13f&lX&#e3d94d&lỉ&#fdd05c&lu &b#%session% &7| %result% &e%numberOfPlayers% &fwinners %currencySymbol%%money%'
      color: RESULT-COLOR
      result-color-setting:
        xiu: GREEN
        tai: RED
      style: SOLID

# Message and bossbar toggle settings
toggle-settings:
  auto-toggle: true  # Auto-enable notifications when player joins game

# Used to track the number of players using the Tai Xiu plugin
# Has no performance impact — thanks for using the plugin.
bStats:
  enabled: true